### PR TITLE
Fix from first code review

### PR DESCRIPTION
**Pull request by ShirleyCsh**

### CODE REVIEW

**Comment by RyanSCollins** [comment]
Fixes for a PR review should go in the same branch as the original PR. This helps both the code reviewer and the developer for a few reasons: (1) it prevents new feature changes (like your java servlet changes) from leaking into the existing PR and extending the length of the PR review; (2) it allows the reviewer to see the diff between the initial PR and the changes; (3) it lets the reviewer see their initial comments when examining the change (and when juggling a lot of reviews it's not always easy to remember what needed to be addressed).

So basically when addressing fixes:
(1) checkout the PR branch (the branch name is also viewable in github in the PR list)
(2) make changes that address the comment
(3) push to github and comment on the PR that comments have been addressed
(4) merge PR into the main branch after it has been approved

This is the same as the feature branch workflow here: https://sites.google.com/sps-program.com/students/technical-resources/common-git-workflows#h.p_JWQx5Z1MLTDS

If you're having trouble managing the branches between the local machine and remote github.com let me know and I can try to come up with some more pointers.

**Comment by ShirleyCsh** [comment]
Thank you for your feedback. I'm not sure why I was not able to see the edit branch I used to push my code at the first time when I do **git branch -a**. I think it might be because I push from my terminal on my local machine?

**Comment by RyanSCollins** [comment]
Hmm... I might have a skipped a step when we were setting up the remote branches the other day. You do want to have both the remote and local branches with the same names for simpler management. You normally do that by 
(1) creating the local branch with "git checkout -b <new_branch_name>"
(2) edit and commit stuff locally
(3) push to the remote branch with "git push origin <new_branch_name>"

How about for now can you move the Java servlet changes to a new branch and remove them from this branch? I'll review the other stuff in this branch. Then when pushing the servlet changes to github, you can name that branch name to match the local branch name.

**Comment by ShirleyCsh** [comment]
Oh I see... I just deleted what I did for week 2 and with the fixes from week 1 in this branch. I will create a new branch to work on week 2 stuff. Thanks!

**Review by RyanSCollins — APPROVED** [review]

**Pull request merged**
